"""initial_migration

Revision ID: b531bb528c7c
Revises: 
Create Date: 2026-07-11 16:11:38.899501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b531bb528c7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('merchant_category', sa.String(length=50), nullable=False),
    sa.Column('merchant_country', sa.String(length=2), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('ip_country', sa.String(length=2), nullable=False),
    sa.Column('card_present', sa.Boolean(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('rule_scores', sa.JSON(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('avg_transaction_amount', sa.Float(), nullable=True),
    sa.Column('std_transaction_amount', sa.Float(), nullable=True),
    sa.Column('tx_count_24h', sa.Integer(), nullable=True),
    sa.Column('tx_count_7d', sa.Integer(), nullable=True),
    sa.Column('tx_count_30d', sa.Integer(), nullable=True),
    sa.Column('unique_merchants_30d', sa.Integer(), nullable=True),
    sa.Column('unique_countries_30d', sa.Integer(), nullable=True),
    sa.Column('unique_devices_30d', sa.Integer(), nullable=True),
    sa.Column('last_tx_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tx_amount', sa.Float(), nullable=True),
    sa.Column('last_tx_country', sa.String(length=2), nullable=True),
    sa.Column('last_tx_device', sa.String(length=100), nullable=True),
    sa.Column('preferred_channels', sa.JSON(), nullable=True),
    sa.Column('preferred_merchants', sa.JSON(), nullable=True),
    sa.Column('home_country', sa.String(length=2), nullable=True),
    sa.Column('home_city', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('rule_scores', sa.JSON(), nullable=True),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('triggered_rules', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
